name: send message when pull request has new comment

on: 
  issue_comment:
    branches-ignore:
      - 'txm**'
      - 'zwp**'

jobs:
  send_message:
    runs-on: Windows
    steps:
    - name: Get Current Code
      run: |
         if (Test-Path viewer_auto_test) 
         {
            Remove-Item viewer_auto_test -Recurse -Force 
         }
         git clone git@github.com:exampler0906/viewer_auto_test.git
      working-directory: ./

    - name: Send Message And Create Label 
      run: |
         cd viewer_auto_test/ci_script
         python send_message_and_create_label.py ${{ github.event.pull_request.title }} ${{ github.event.review.body }} ${{secrets.VIEWER_TOKEN}}
      working-directory: ./