name: send message when pull request has new comment

on: 
  issue_comment:
    branches-ignore:
      - 'txm**'
      - 'zwp**'

jobs:
  send_message:
    runs-on: Windows
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: Get Current Code
      run: |
         if (Test-Path viewer_auto_test) 
         {
            Remove-Item viewer_auto_test -Recurse -Force 
         }
         git clone git@github.com:exampler0906/viewer_auto_test.git
      working-directory: ./

    - name: Send Message And Create Label 
      run: |
         cd viewer_auto_test/ci_script
         echo "${{ github.event.issue.pull_request }}"
         echo "${{ github.event.issue.pull_request.html_url }}"
         echo "${{ github.event.issue.pull_request.number }}"
         echo "${{ github.event.issue.pull_request.title }}"
         echo "${{ github.event.issue.pull_request.body }}"
         echo "${{ github.event.issue.pull_request.state }}"
         echo "${{ github.event.issue.pull_request.locked }}"
         echo "${{ github.event.issue.pull_request.created_at }}"
         echo "${{ github.event.issue.pull_request.updated_at }}"
         echo "${{ github.event.issue.pull_request.closed_at }}"
         echo "${{ github.event.issue.pull_request.merged_at }}"
         echo "${{ github.event.issue.pull_request.draft }}"
         echo "${{ github.event.issue.pull_request.author_association }}"
         echo "${{ github.event.issue.review.body }}"
         echo "${{ secrets.VIEWER_TOKEN }}"
         python send_message_and_create_label.py ${{ github.event.issue.pull_request.title }} ${{ github.event.issue.review.body }} ${{ secrets.VIEWER_TOKEN }}
      working-directory: ./