name: send message when pull request has new comment

on: 
  issue_comment:
    branches-ignore:
      - 'tmx**'
      - 'zwp**'

jobs:
  send_message:
    runs-on: Windows
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: Get Current Code
      run: |
         if (Test-Path viewer_auto_test)
         {
            cd viewer_auto_test
            git checkout . 
            git clean -df
            git checkout -b temp
            git fetch origin master::master
            git checkout master
            git branch -D temp
         }
         else
         {
            git clone git@github.com:exampler0906/viewer_auto_test.git
         }
      working-directory: ./

    - name: Send Message And Create Label 
      run: |
         cd viewer_auto_test/ci_script
         python send_message_and_create_label.py "${{ github.event.issue.pull_request.html_url }}" "${{ github.event.comment.body }}" "${{ secrets.VIEWER_TOKEN }}"
      working-directory: ./
